# Generated by Django 3.2.8 on 2021-11-11 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='blog_articles', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
