# Generated by Django 3.2.8 on 2021-10-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_auto_20211030_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
