# Generated by Django 3.2.8 on 2021-11-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
