# Generated by Django 3.2.8 on 2021-11-20 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serials', '0006_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
    ]
